### GET /products
GET http://localhost:8080/products

### GET /products?active=true
GET http://{{server}}:{{port}}/products?active=true

### GET /products?active=true
GET http://localhost:8080/products?active=true

### POST /products
POST http://localhost:8080/products
Content-Type: application/json

{
"title": "<Milk 3.8>",
"price": 1.96,
"activ": false
}

### PUT /products
PUT http://localhost:8080/products/2
Content-Type: application/json

{
  "title": "Milk 1.5",
  "price": 1.06,
  "activ": true
}